//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaHtmlEditControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaHtmlEditControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string HtmlEditControl_ExecuteSystemInfo_Information {
            get {
                return ResourceManager.GetString("HtmlEditControl_ExecuteSystemInfo_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非预期的路径 &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MyModule_Process_Unexpected_path___0___ {
            get {
                return ResourceManager.GetString("MyModule_Process_Unexpected_path___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须提供一个HtmlTemplate值 的本地化字符串。
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少“##BODY##&apos;的HTML模板属性值. 的本地化字符串。
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Center {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Justify {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Left {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Right {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_CellProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ColumnProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_ColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arial 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyArial {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyArial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Courier new 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyCourierNew {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyCourierNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Garamond 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGaramond {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGaramond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Georgia 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGeorgia {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGeorgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Times 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyTimes {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verdana 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyVerdana {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyVerdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize4 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize5 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize6 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize7 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSizeStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSizeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 &lt;address&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleAddress {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预格式 &lt;pre&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleFormatted {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 1 &lt;h1&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 2 &lt;h2&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 3 &lt;h3&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleNormal {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 段落 &lt;p&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleParagraph {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AbsBottom 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AbsMiddle 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基线 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBaseLine {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底端 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居左 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignLeft {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居右 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignRight {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本顶端 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTextTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_RowProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_RowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_TableProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基线 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_BaseLine {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_BaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底端 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Bottom {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Middle {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Top {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获得空闲端口. 的本地化字符串。
        /// </summary>
        internal static string WebServer_getFreePort_Unable_to_acquire_free_port_ {
            get {
                return ResourceManager.GetString("WebServer_getFreePort_Unable_to_acquire_free_port_", resourceCulture);
            }
        }
    }
}
